### ISSUE TITLE
Daily coding challenges

### ISSUE THREAD

**Issue by madhead** [JavaBy/opinions-bot#27]
Подсмотрено у vas3k:

> - Чтобы не выгореть, решаем по одной задаче в день: утром постим ссылку на литкод, а вечером все показывают свои решения. До вечера обсуждения решений запрещены, можно обсуждать только тайминги и алгоритмическую сложность.
> - Чтобы была мотивация что-то делать, тех, кто не решает задачи дольше недели, кикаем из чата.
> - Чтобы чат не вырождался, будем держать число участников ограниченным, не больше 20 человек.
> 
> Быстро всплыло несколько проблем: Я забывал постить задачи утром. Люди решали что-то днём, но посылали решения в чат только заполночь, и никакого обсуждения не получалось. Отлавливать прогульщиков поиском последних сообщений было муторно.
> 
> Решили это автоматизацией: я сделал маленький сайт (на всратом anvil.works), где админы могли планировать список задач хоть на ближайший месяц, а пользователи — вставлять ссылки на pastebin и любоваться на табличку «какие задачи я решил за последние 7 дней». Теперь утром бот приносил в чат задачу, в течение дня принимал ссылки на решения в формочку на сайте и в шесть вечера постил всё собранное в чат.
> 
> Попутно нашлось ещё два человека, желающих помогать с выбором задач, мы подобрали устраивающий всех уровень сложности (две изи задачи по выходным, один хард и четыре медиума на неделе), кикнули из чата десяток лентяев, и даже сходили всей толпой на хайринг ивент Амазона в Амстердаме. Устроили несколько оффлайн-сходок, пережили парочку сезонных спадов и попыток переключиться с литкода на что-нибудь другое, и, конечно же, обросли толстым слоем местечковых мемов.
> 
> Сейчас проекту 15 месяцев, и из того, чем можно было бы похвастаться я бы выделил следующее:
> 
> - Получилось создать живое и самоподдерживающееся сообщество друзей. В чате, кроме задач, обсуждают, где провести отпуск, помогают друг другу с переездами, и ищут лучший рамен в Амстердаме.
> - Про попытки и результаты некоторые товарищи скромно молчат, но я точно знаю про офферы от FB, Amazon, Apple и Spotify участникам чата.
> - Благодаря этому проекту, я научился клепать сайтики на джанге и писать бинарный поиск с первого раза без ошибок.
> 
> Из идей на будущее:
> 
> - Получше интегрироваться с телеграмом, автоматизировать кик из чата за неактивность, например.
> - Насыпать каких-нибудь рейтингов и геймификаций. (мне это кажется дичью, но некоторые пользователи требуют)
> - Добавить обратной связи для составителей подборок задач, а лучше вообще перейти на автоматический подбор задач с каким-нибудь ML.
> 
> Но вообще я доволен текущей ситуацией, и не думаю, что нам нужны какие-то новые технические фишки. А для кодинга в свободное время я уже другой пет-проджект начал.
> 
> Есть ещё идея сделать похожий чат, но решать там задачи из SICP во имя духовного совершенствования и усмирения гордыни. То есть как «есть идея» — я уже несколько раз начинал об этом разговор, и теперь жду, когда кто-нибудь создаст этот чат вместо меня. Лучший способ быть успешным фаундером — делегировать задачи, не так ли?
>

**Comment by wtsiamruk** [comment]
"Чтобы была мотивация что-то делать, тех, кто не решает задачи дольше недели, кикаем из чата."

Предполагается иметь отдельный чат?

**Comment by madhead** [comment]
Специфика этого чела, что он изначально затевал это в непрофильном чате у эмигрантов-айтишников.

**Comment by wtsiamruk** [comment]
Как думаешь, как лучше в случае с нашим профильным сообществом поступить? Есть идеи? В чате можно делать сообщения с комментариями внутр к сообщению как в новостных группах, если можно то это неплохой вариант :)

**Comment by madhead** [comment]
Вообще, не хотелось бы делать "отдельный" чат или канал по причинам:

- Не хочется распылять аудиторию, хочется, чтобы было ядро в виде чата
- Не думаю, что этим заинтересуется прям много людей (активных и так немного, см стат-бота)
- И в то же время эта фича могла бы как раз "активировать" чат

Насколько мне известно, сообщения к соощению как раз и ведут из канала в группу (чат), а у нас уже чат. В чатах не видел, чтобы были обсуждения. Но если сделать канал и прикрутить к нему чат как группу для обсуждения и репостить из канала в чат…

Но ИМХО это всё сложно и можно начать с простых сообщений в чате.
