### ISSUE TITLE
Post new Inside Java podcasts automatically.

### ISSUE THREAD

**Issue by madhead** [JavaBy/opinions-bot#32]
[They](https://inside.java/podcast) have an RSS feed: http://insidejava.libsyn.com/rss.

Why not schedule another function to check it regularly and post new episodes automatically?

**Comment by sleshJdev** [comment]
I have wrote them letter some time ago to ask if they have webhook or an another way to implement 'push' model to implement notification in more efficient - unfortunately, they don't. Implementing it in the way you have suggested it's fine too. Btw, I think we can have it built into current lambda:
```
on_new_message
  process message regularly
  if now - rss_pull_last_time > 1day
    pull rss
    if rss_has_something_new
      process rss additionally and send update into chat
```

The only problem with this approach we cannot guarantee any schedule and predictiveness. No rss will be process until someone text something in the chat.

**Comment by madhead** [comment]
That's actually an interesting idea, allowing to simplify the setup.

I was thinking about storing "seen" episodes in DynamoDB and process the RSS regularly by cron with CloudWatch…
